AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the time
Resources:
  TimeFunction:
    Properties:
      CodeUri: s3://norbit-production/4ff3c69a411587d3335085e331768be1
      Events:
        MyTimeApi:
          Properties:
            Method: GET
            Path: /TimeResource
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
